#!/bin/bash
fullpath=$(realpath $(dirname $0))
cd $fullpath
[[ -x clean ]] && ./clean
mkdir -p obj lib bin
gcc -c identity.c -o obj/identity.o
ar rcs lib/libidentity.a obj/identity.o
rustc --crate-type=bin -o bin/rusticles main.rs -Llib
# gcc -fPIC -c main.c -o obj/main.o
# LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${fullpath}/lib
[[ -x bin/rusticles ]] && ./bin/rusticles || exit 1
