#!/bin/bash
fullpath=$(realpath $(dirname $0))
cd $fullpath
[[ -x clean ]] && ./clean
mkdir -p obj lib bin
gcc -c identity.c -o obj/identity.o
#NOTE overriding the invocation of rustfmt b/c it complains about deprecation and fails for bindgen....
#NOTE rustfmt-nightly is the non-deprecated equivalent of the tool, but did not compile & install properly
bindgen --no-rustfmt-bindings identity.h 2>/dev/null | rustfmt --force > identity.rs
ar rcs lib/libidentity.a obj/identity.o
rustc --crate-type=bin -o bin/rusticles main.rs -Llib -lidentity
[[ -x bin/rusticles ]] && ./bin/rusticles || exit 1
