#!/bin/bash
fullpath=$(realpath $(dirname $0))
cd $fullpath
[[ -x clean ]] && ./clean
mkdir -p obj lib bin
gcc -o lib/libidentity.so -shared -fPIC -g -I. identity.c 
csc -s test.scm -Llib #-dry-run
#-uses identity
