#!/bin/bash
fullpath=$(realpath $(dirname $0))
cd $fullpath
[[ -x clean ]] && ./clean
mkdir -p obj lib bin
gcc -c identity.c -o obj/identity.o
gcc -shared -o lib/libidentity.so obj/identity.o
scheme --script main.scm
