#!/bin/bash -e
fullpath=$(realpath $(dirname $0))
cd $fullpath
[[ -x clean ]] && ./clean
mkdir -p bin obj lib
ecl -o lib/libidentity.so -compile identity.lisp >/dev/null
gcc -fPIC -c main.c -o obj/main.o
gcc -o bin/identity -Wl,-rpath=${fullpath}/lib -Wl,--no-undefined obj/main.o -Llib -lidentity
[[ -x bin/identity ]] && ./bin/identity || exit 1
